### ISSUE TITLE
['suggestion 1', 'suggestion 2', 'suggestion 3', ...] 

### ISSUE THREAD

**Issue by gasyoun** [Pixabay/jQuery-autoComplete#16]
Hi,

 If I have list of 400 000 words (plain .txt file), can I lookup in the list, not to provide an array? Based on the alphabet there can be 50 smaller lists, but anyway I can't list all of them in arrays, they would be too clumsy.

Thanks

**Comment by SimonSteinberger** [comment]
I think that's a case for Ajax requests! Assuming an average word length of 8 characters (+2 characters per word for quotes), your document size would exceed 4 MB. That itself is rather much, yet, it can work. However, executing that mass of code is probably a bad idea, because there's usually a performance issue.
