### ISSUE TITLE
Pressing Enter doesn't call onSelect

### ISSUE THREAD

**Issue by adam-lynch** [Pixabay/jQuery-autoComplete#6]
I can't even find `13` (the keycode for `enter`) anywhere in the code. It does put the item's text in the field, but I can't see where it does that.

**Comment by SimonSteinberger** [comment]
We try to keep the plugin as simple and efficient as possible. Therefore, the onSelect callback is only fired on mouse click/select.

From the docs:
"A callback function that fires when a suggestion is selected by mouse click."

AFAICS, the callback has just one use case: You can submit the form on select. That's how we use it on Pixabay. By doing that, the mouse click has an identical behavior like pressing enter on a regular form. As it is, the plugin doesn't interfere in the normal form field behavior. The form gets submitted when pressing enter. Additionally, you can bind all kinds of event handler on the input field directly.

So, it's intentional, but we might change this if it's important. It doesn't involve a lot of overhead, but some ... Closing the issue for now.

**Comment by adam-lynch** [comment]
I don't think any of those options work for my use case. I want to get a callback whenever a suggestion is selected. It has nothing to do with submitting the form. If #8 is merged, then when you click a suggestion, `onSelect` will be called with the text and the suggestion. If you press enter to select (plenty of people would), then you get nothing, `onSelect` isn't called. I think it'll be trivial to add, I'll see can I create a PR in a minute.

**Comment by adam-lynch** [comment]
See #9.

**Comment by SimonSteinberger** [comment]
Yes, it's simple to add and it wouldn't cause a lot of overhead. We would include this feature *right away* if a few people preferred to have it.

I think it *can* be useful and maybe it's even important to always fire the onSelect callback. But it's also important to keep the plugin as tiny as possible. There are quite a few suggester plugins available with lots and lots of options, but they usually come with the price of a huge code base, e.g. jQuery UI autocomplete: http://jqueryui.com/autocomplete/

We'll definitely think about it - and if others join in, we'll certainly include the feature!

**Comment by Hacktivista** [comment]
I think onSelect should always be triggered when something is selected, why not?

**Comment by havramar** [comment]
:+1:

**Comment by oshihirii** [comment]
+1 for onSelect being triggered by pressing Enter.

**Comment by oshihirii** [comment]
For those looking, the [devbridge autocomplete plugin](https://github.com/devbridge/jQuery-Autocomplete) has this behaviour by default, I have put together heavily commented [codepen demo here](https://codepen.io/oshihirii/full/EvMjZm).
